name: deploy-gradle-kts-sample
on:
  push:
    tags: '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: olegtarasov/get-tag@v1
      - name: deploy-release
        run: gradle-kts-sample/.buildsystem/deploy.sh
        env:
          GITHUB_MAVEN_USERNAME: ${{ secrets.GITHUB_MAVEN_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_RELEASES_URL: https://maven.pkg.github.com/atlassian/packages-maven
  test-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: deploy-release
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
